### ISSUE TITLE
Arena-name in Location

### ISSUE THREAD

**Issue by Backeman** [theseal/hockey-mchockeyface#7]
I would like the name of the Arena the game is played at, in the Location-field of the event.

**Comment by kokarn** [comment]
This would be great but the calendar we use as source doesn't provide that information. 

What we could do is just assume home-team is playing in their arena but that doesn't work very well for teams with multiple arenas like DIF & FHC.

Thoughts @theseal ?

**Comment by theseal** [comment]
I'm not sure how SHL manage the official feed because the feed today includes 368 games and only two of them include the location. It's a bit strange…
```
curl -silent -L  https://www.google.com/calendar/ical/hockeyligan.sverige@gmail.com/public/basic.ics | grep LOCATION: | egrep -v "LOCATION:\r"
LOCATION:COOP Norrbotten Arena
LOCATION:Skellefteå Kraft Arena
```
We can as @kokarn says guess and get a pretty good success rate. But I think that the guess could fail even for teams other then DIF and FHC. If we would guess the location I think we should add a note in DESCRIPTION that the location is not 100% accurate.

Is it a good idea to report this back to SHL and ask them to fix the issue?

**Comment by kokarn** [comment]
I'd rather not add something that's inaccurate. Reporting to SHL or using some other source (SHL API?) for it is probably better.

**Comment by theseal** [comment]
The API sounds like something to investigate more. :)

**Comment by kokarn** [comment]
You can easily ask for a key here http://doc.openapi.shl.se/

**Comment by theseal** [comment]
I will look in to that. :)

**Comment by kokarn** [comment]
This is implemented for SHL since https://github.com/theseal/hockey-mchockeyface/commit/15a08f03ea99193bc5da0f91a7550639c0d93460.
